### ISSUE TITLE
about img2vidpika.sh

### ISSUE THREAD

**Issue by 844704781** [Ug0Security/txt2porngif#2]
Hello, I have read your img2vidpika.sh code, but I did not find any API to obtain the progress of video generation. Your code logic tries to obtain video results multiple times, sometimes waiting for 5 seconds, sometimes waiting for 20 seconds. Is there an API to obtain the progress of video generation? But I did not find it.

**Comment by Ug0Security** [comment]
i don't know if there is one, i've lost interest in pika since it's now limited for free users (did it changed ?)

anyway i made a shitty loop to avoid that. 

from my experience it used be to somewhere bewteen 60 and 120 sec for each img2vid

**Comment by 844704781** [comment]
> progress

Thanks I found the progress Field I wanted yesterday
